import React from 'react';
import { Save, RotateCcw, Plus, Trash2, ExternalLink, Image, Video, CalendarDays, Music2, Type, Settings, Smartphone, Images, LogIn, LogOut, Upload, UserPlus, BriefcaseBusiness } from 'lucide-react';
import { loadContent, saveContent, resetContent, getAdminSession, adminLogin, adminLogout, adminSignUp, bootstrapAdmin, checkAdmin, uploadMedia, fetchRemoteContent } from './contentStore';

function Field({label,value,onChange,textarea=false,type='text'}){return <label className="adminField"><span>{label}</span>{textarea?<textarea value={value||''} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/>}</label>}
function Check({label,checked,onChange}){return <label className="adminCheck"><input type="checkbox" checked={Boolean(checked)} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function UploadField({label,value,onChange,folder}){const[busy,setBusy]=React.useState(false);const[msg,setMsg]=React.useState('');const handle=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setMsg('');try{const url=await uploadMedia(file,folder);onChange(url);setMsg('Upload concluído.');}catch(err){setMsg(err.message||'Falha no upload.')}finally{setBusy(false)}};return <div className="adminUpload"><Field label={label} value={value} onChange={onChange}/><label className="uploadBtn"><Upload size={15}/>{busy?'Enviando...':'Enviar arquivo'}<input type="file" hidden onChange={handle} disabled={busy}/></label>{msg&&<small>{msg}</small>}</div>}

export default function Admin(){
  const[content,setContent]=React.useState(loadContent());const[tab,setTab]=React.useState('geral');const[notice,setNotice]=React.useState('');const[session,setSession]=React.useState(getAdminSession());const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[loginError,setLoginError]=React.useState('');const[mode,setMode]=React.useState('login');const[checking,setChecking]=React.useState(true);
  React.useEffect(()=>{fetchRemoteContent().then(setContent)},[]);
  React.useEffect(()=>{(async()=>{if(!session){setChecking(false);return;}const ok=await checkAdmin(session);if(!ok){adminLogout();setSession(null);}setChecking(false)})()},[]);
  const patch=(section,key,value)=>setContent(v=>({...v,[section]:{...v[section],[key]:value}}));
  const save=async()=>{try{const result=await saveContent(content);setNotice(result.remote?'Alterações publicadas no site.':'Alterações salvas localmente. Faça login para publicar.');}catch(err){setNotice(err.message||'Erro ao publicar.')}setTimeout(()=>setNotice(''),3500)};
  const reset=()=>setContent(resetContent());
  const mutateList=(name,i,key,value)=>setContent(v=>({...v,[name]:v[name].map((x,idx)=>idx===i?{...x,[key]:value}:x)}));
  const removeList=(name,i)=>setContent(v=>({...v,[name]:v[name].filter((_,idx)=>idx!==i)}));
  const addShow=()=>setContent(v=>({...v,shows:[...v.shows,{id:`show-${Date.now()}`,date:'',time:'21:00',city:'',state:'SP',venue:'',address:'',ticketUrl:'',private:false,visible:false}]}));
  const addVideo=()=>setContent(v=>({...v,videos:[...v.videos,{id:`video-${Date.now()}`,title:'',youtubeUrl:'',thumbnailUrl:''}]}));
  const addRelease=()=>setContent(v=>({...v,music:{...v.music,releases:[...v.music.releases,{id:`release-${Date.now()}`,type:'Single',year:new Date().getFullYear().toString(),title:'',spotifyUrl:'',coverUrl:''}]}}));
  const updateRelease=(i,key,value)=>setContent(v=>({...v,music:{...v.music,releases:v.music.releases.map((r,idx)=>idx===i?{...r,[key]:value}:r)}}));
  const removeRelease=i=>setContent(v=>({...v,music:{...v.music,releases:v.music.releases.filter((_,idx)=>idx!==i)}}));
  const login=async e=>{e.preventDefault();setLoginError('');try{const s=await adminLogin(email,password);let isAdmin=await checkAdmin(s);if(!isAdmin){try{await bootstrapAdmin(s);isAdmin=await checkAdmin(s);}catch{isAdmin=false;}}if(!isAdmin){adminLogout();throw new Error('Este usuário não possui acesso administrativo.');}setSession(s);setContent(await fetchRemoteContent());}catch(err){setLoginError(err.message||'Não foi possível entrar.')}};
  const signup=async e=>{e.preventDefault();setLoginError('');try{const result=await adminSignUp(email,password);if(result.needsConfirmation){setLoginError('Conta criada. Confirme o e-mail recebido e depois entre normalmente.');return;}await bootstrapAdmin(result.session);setSession(result.session);setContent(await fetchRemoteContent());}catch(err){setLoginError(err.message||'Não foi possível criar o primeiro acesso.')}};
  const logout=()=>{adminLogout();setSession(null)};
  const tabs=[['geral',Settings,'Geral'],['midia',Images,'Mídia'],['hero',Type,'Hero'],['musica',Music2,'Música'],['agenda',CalendarDays,'Agenda'],['videos',Video,'Vídeos'],['sobre',Image,'Sobre'],['mobile',Smartphone,'Mobile']];
  if(checking)return <div className="adminLogin"><form><span className="adminEyebrow">CMS OFICIAL</span><h1>Lucas Venutto</h1><p>Carregando painel...</p></form></div>;
  if(!session)return <div className="adminLogin"><form onSubmit={mode==='login'?login:signup}><span className="adminEyebrow">CMS OFICIAL</span><h1>Lucas Venutto</h1><p>{mode==='login'?'Entre com o usuário administrador do site.':'Crie o primeiro usuário administrador.'}</p><Field label="E-mail" type="email" value={email} onChange={setEmail}/><Field label="Senha" type="password" value={password} onChange={setPassword}/>{loginError&&<div className="adminNotice error">{loginError}</div>}<button className="primary" type="submit">{mode==='login'?<LogIn size={16}/>:<UserPlus size={16}/>} {mode==='login'?'Entrar':'Criar primeiro acesso'}</button><button className="ghost" type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setLoginError('')}}>{mode==='login'?'Criar primeiro acesso':'Já tenho usuário'}</button><a href="/">Voltar ao site</a></form></div>;
  return <div className="adminShell"><aside className="adminSidebar"><div><strong>Lucas Venutto</strong><small>Painel do site</small></div>{tabs.map(([id,Icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}<a className="adminCommercialLink" href="/admin/contratantes"><BriefcaseBusiness size={17}/>Contratantes</a><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={17}/>Ver site</a><button onClick={logout}><LogOut size={17}/>Sair</button></aside>
  <main className="adminMain"><header className="adminTop"><div><span className="adminEyebrow">CMS</span><h1>Gerenciar site</h1></div><div className="adminTopActions"><button onClick={reset} className="ghost"><RotateCcw size={16}/>Restaurar</button><button onClick={save} className="primary"><Save size={16}/>Publicar</button></div></header>{notice&&<div className="adminNotice">{notice}</div>}
  {tab==='geral'&&<section className="adminPanel"><h2>Identidade e contato</h2><div className="adminGrid"><Field label="Nome do artista" value={content.brand.artist} onChange={v=>patch('brand','artist',v)}/><Field label="Slogan" value={content.brand.tagline} onChange={v=>patch('brand','tagline',v)}/><Field label="WhatsApp" value={content.booking.whatsapp} onChange={v=>patch('booking','whatsapp',v)}/><Field label="E-mail" value={content.booking.email} onChange={v=>patch('booking','email',v)}/></div><h3>Redes</h3><div className="adminGrid"><Field label="Instagram" value={content.social.instagram} onChange={v=>patch('social','instagram',v)}/><Field label="TikTok" value={content.social.tiktok} onChange={v=>patch('social','tiktok',v)}/><Field label="YouTube" value={content.social.youtube} onChange={v=>patch('social','youtube',v)}/><Field label="Facebook" value={content.social.facebook} onChange={v=>patch('social','facebook',v)}/></div></section>}
  {tab==='midia'&&<section className="adminPanel"><h2>Mídia e logos</h2><p className="adminHelp">Envie imagens otimizadas em WebP/AVIF sempre que possível. O site não carrega mais os logos antigos de 9–10 MB como fallback.</p><div className="adminGrid"><UploadField label="Logo cabeçalho" value={content.media.headerLogoUrl} onChange={v=>patch('media','headerLogoUrl',v)} folder="logos"/><UploadField label="Logo principal hero" value={content.media.heroLogoUrl} onChange={v=>patch('media','heroLogoUrl',v)} folder="logos"/><UploadField label="Foto do hero" value={content.media.heroImageUrl} onChange={v=>patch('media','heroImageUrl',v)} folder="hero"/><UploadField label="Foto da história" value={content.media.storyImageUrl} onChange={v=>patch('media','storyImageUrl',v)} folder="sobre"/><UploadField label="Capa da seção Vídeos" value={content.media.videoCoverUrl} onChange={v=>patch('media','videoCoverUrl',v)} folder="videos"/></div></section>}
  {tab==='hero'&&<section className="adminPanel"><h2>Primeira tela</h2><div className="adminGrid"><Field label="Selo superior" value={content.hero.eyebrow} onChange={v=>patch('hero','eyebrow',v)}/><Field label="Título" value={content.hero.title} onChange={v=>patch('hero','title',v)}/><Field label="Subtítulo" value={content.hero.subtitle} onChange={v=>patch('hero','subtitle',v)}/><Field label="Texto botão principal" value={content.hero.primaryLabel} onChange={v=>patch('hero','primaryLabel',v)}/></div></section>}
  {tab==='musica'&&<section className="adminPanel"><div className="adminPanelHead"><h2>Música e discografia</h2><button className="smallPrimary" onClick={addRelease}><Plus size={15}/>Novo lançamento</button></div><div className="adminGrid"><Field label="Título da seção" value={content.music.title} onChange={v=>patch('music','title',v)}/><Field label="Spotify artista" value={content.music.spotifyArtistUrl} onChange={v=>patch('music','spotifyArtistUrl',v)}/><Field label="Spotify URI" value={content.music.spotifyArtistUri} onChange={v=>patch('music','spotifyArtistUri',v)}/><Field label="Texto de apoio" textarea value={content.music.intro} onChange={v=>patch('music','intro',v)}/></div>{content.music.releases.map((r,i)=><div className="adminItem" key={r.id}><div className="adminGrid"><Field label="Título" value={r.title} onChange={v=>updateRelease(i,'title',v)}/><Field label="Tipo (Single/EP/Álbum)" value={r.type} onChange={v=>updateRelease(i,'type',v)}/><Field label="Ano" value={r.year} onChange={v=>updateRelease(i,'year',v)}/><Field label="Spotify" value={r.spotifyUrl} onChange={v=>updateRelease(i,'spotifyUrl',v)}/><UploadField label="Capa oficial" value={r.coverUrl} onChange={v=>updateRelease(i,'coverUrl',v)} folder="capas"/></div><button className="danger" onClick={()=>removeRelease(i)}><Trash2 size={15}/>Excluir</button></div>)}</section>}
  {tab==='agenda'&&<section className="adminPanel"><div className="adminPanelHead"><div><h2>Agenda</h2><p className="adminHelp">Cadastre o evento internamente e ative “Exibir no site” somente quando estiver pronto para divulgação.</p></div><button className="smallPrimary" onClick={addShow}><Plus size={15}/>Novo show</button></div>{content.shows.length?content.shows.map((s,i)=><div className="adminItem" key={s.id}><div className="adminCheckboxes"><Check label="Exibir no site" checked={s.visible} onChange={v=>mutateList('shows',i,'visible',v)}/><Check label="Evento privado" checked={s.private} onChange={v=>mutateList('shows',i,'private',v)}/></div><div className="adminGrid"><Field label="Data" type="date" value={s.date} onChange={v=>mutateList('shows',i,'date',v)}/><Field label="Hora" type="time" value={s.time} onChange={v=>mutateList('shows',i,'time',v)}/><Field label="Cidade" value={s.city} onChange={v=>mutateList('shows',i,'city',v)}/><Field label="UF" value={s.state} onChange={v=>mutateList('shows',i,'state',v)}/><Field label="Local" value={s.venue} onChange={v=>mutateList('shows',i,'venue',v)}/><Field label="Endereço" value={s.address} onChange={v=>mutateList('shows',i,'address',v)}/><Field label="Link ingresso" value={s.ticketUrl} onChange={v=>mutateList('shows',i,'ticketUrl',v)}/></div><button className="danger" onClick={()=>removeList('shows',i)}><Trash2 size={15}/>Excluir</button></div>):<p className="adminHelp">Nenhum show cadastrado. A Home mostrará “Novas datas em breve”.</p>}</section>}
  {tab==='videos'&&<section className="adminPanel"><div className="adminPanelHead"><h2>Vídeos</h2><button className="smallPrimary" onClick={addVideo}><Plus size={15}/>Novo vídeo</button></div>{content.videos.map((v,i)=><div className="adminItem" key={v.id}><div className="adminGrid"><Field label="Título" value={v.title} onChange={x=>mutateList('videos',i,'title',x)}/><Field label="Link YouTube" value={v.youtubeUrl} onChange={x=>mutateList('videos',i,'youtubeUrl',x)}/><UploadField label="Thumbnail" value={v.thumbnailUrl} onChange={x=>mutateList('videos',i,'thumbnailUrl',x)} folder="thumbs"/></div><button className="danger" onClick={()=>removeList('videos',i)}><Trash2 size={15}/>Excluir</button></div>)}</section>}
  {tab==='sobre'&&<section className="adminPanel"><h2>Sobre e imprensa</h2><Field label="Título sobre" value={content.about.title} onChange={v=>patch('about','title',v)}/><Field label="Biografia curta" textarea value={content.about.text} onChange={v=>patch('about','text',v)}/><Field label="Título imprensa" value={content.press.title} onChange={v=>patch('press','title',v)}/><Field label="Texto imprensa" textarea value={content.press.text} onChange={v=>patch('press','text',v)}/><Field label="Press kit" value={content.press.pressKitUrl} onChange={v=>patch('press','pressKitUrl',v)}/><Field label="Rider técnico (privado/contratantes)" value={content.press.riderUrl} onChange={v=>patch('press','riderUrl',v)}/><Field label="Mapa de palco" value={content.press.stageMapUrl} onChange={v=>patch('press','stageMapUrl',v)}/><Field label="Material de divulgação" value={content.press.promoMaterialUrl} onChange={v=>patch('press','promoMaterialUrl',v)}/></section>}
  {tab==='mobile'&&<section className="adminPanel"><h2>Experiência mobile</h2><p className="adminHelp">No celular o Hero é mais curto, a letra rolante é ocultada, a navegação inferior respeita a safe-area do iPhone e o player fica acima dela.</p><div className="mobilePreview"><div className="phoneMock"><span>{content.hero.eyebrow}</span><strong>{content.hero.title}</strong><small>{content.brand.tagline}</small><button>▶ {content.hero.primaryLabel}</button></div></div></section>}
  </main></div>;
}
