import React from 'react';
import { BriefcaseBusiness, CalendarDays, FileText, LogIn, LogOut, MapPin, Save, TicketCheck, UserPlus } from 'lucide-react';
import { contractorLogin, contractorLogout, contractorSignUp, fetchContractorJobs, fetchContractorProfile, getContractorSession, updateContractorProfile } from './contractorStore';

function Field({label,value,onChange,type='text'}){return <label className="contractorField"><span>{label}</span><input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
const statusLabel={lead:'Consulta',proposal:'Proposta',negotiation:'Negociação',contract:'Contrato',confirmed:'Confirmado',completed:'Realizado',cancelled:'Cancelado'};

export default function Contractor(){
  const[session,setSession]=React.useState(getContractorSession());
  const[mode,setMode]=React.useState('login');
  const[loading,setLoading]=React.useState(Boolean(session));
  const[error,setError]=React.useState('');
  const[notice,setNotice]=React.useState('');
  const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');
  const[signup,setSignup]=React.useState({name:'',company:'',phone:'',city:'',state:'SP'});
  const[profile,setProfile]=React.useState(null);const[jobs,setJobs]=React.useState([]);

  const load=async s=>{setLoading(true);setError('');try{const[p,j]=await Promise.all([fetchContractorProfile(s),fetchContractorJobs(s)]);if(!p)throw new Error('Cadastro de contratante não encontrado.');setProfile(p);setJobs(j);}catch(e){setError(e.message||'Não foi possível carregar o portal.')}finally{setLoading(false)}};
  React.useEffect(()=>{if(session)load(session)},[]);

  const login=async e=>{e.preventDefault();setError('');try{const s=await contractorLogin(email,password);setSession(s);await load(s);}catch(e){setError(e.message||'Falha no login.')}};
  const signupSubmit=async e=>{e.preventDefault();setError('');try{const r=await contractorSignUp({email,password,...signup});if(r.needsConfirmation){setNotice('Cadastro criado. Confirme seu e-mail e depois entre normalmente.');setMode('login');return;}setSession(r.session);await load(r.session);}catch(e){setError(e.message||'Falha no cadastro.')}};
  const saveProfile=async()=>{try{const p=await updateContractorProfile(profile);setProfile(p);setNotice('Dados atualizados.');setTimeout(()=>setNotice(''),2500)}catch(e){setError(e.message||'Não foi possível salvar.')}};
  const logout=()=>{contractorLogout();setSession(null);setProfile(null);setJobs([])};

  if(!session)return <div className="contractorLogin"><div className="contractorLoginCard"><span className="contractorEyebrow">ÁREA DO CONTRATANTE</span><h1>Lucas Venutto</h1><p>{mode==='login'?'Acompanhe propostas, contratos, dados do evento e materiais do seu show.':'Crie seu acesso de contratante.'}</p><form onSubmit={mode==='login'?login:signupSubmit}><Field label="E-mail" type="email" value={email} onChange={setEmail}/><Field label="Senha" type="password" value={password} onChange={setPassword}/>{mode==='signup'&&<><Field label="Nome" value={signup.name} onChange={v=>setSignup(s=>({...s,name:v}))}/><Field label="Empresa / produtor" value={signup.company} onChange={v=>setSignup(s=>({...s,company:v}))}/><Field label="Telefone" value={signup.phone} onChange={v=>setSignup(s=>({...s,phone:v}))}/><div className="contractorTwo"><Field label="Cidade" value={signup.city} onChange={v=>setSignup(s=>({...s,city:v}))}/><Field label="UF" value={signup.state} onChange={v=>setSignup(s=>({...s,state:v}))}/></div></>}{error&&<div className="contractorAlert error">{error}</div>}{notice&&<div className="contractorAlert">{notice}</div>}<button className="contractorPrimary" type="submit">{mode==='login'?<LogIn size={17}/>:<UserPlus size={17}/>} {mode==='login'?'Entrar':'Criar acesso'}</button><button className="contractorGhost" type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setNotice('')}}>{mode==='login'?'Ainda não tenho acesso':'Já tenho acesso'}</button></form><a href="/">Voltar ao site oficial</a></div></div>;
  if(loading)return <div className="contractorLogin"><div className="contractorLoginCard"><span className="contractorEyebrow">ÁREA DO CONTRATANTE</span><h1>Carregando...</h1></div></div>;

  return <div className="contractorShell"><aside className="contractorSide"><div><strong>Lucas Venutto</strong><small>Portal do contratante</small></div><nav><a href="#resumo">Resumo</a><a href="#eventos">Eventos</a><a href="#dados">Meus dados</a></nav><a href="/">Site oficial</a><button onClick={logout}><LogOut size={16}/>Sair</button></aside><main className="contractorMain"><header className="contractorTop"><div><span className="contractorEyebrow">BEM-VINDO</span><h1>{profile?.name||profile?.company||'Contratante'}</h1><p>{profile?.company}</p></div><div className="contractorStatus"><span>{jobs.length}</span><small>evento(s)</small></div></header>{error&&<div className="contractorAlert error">{error}</div>}{notice&&<div className="contractorAlert">{notice}</div>}
  <section id="resumo" className="contractorSummary"><div><BriefcaseBusiness/><span>Propostas e contratos</span><strong>{jobs.filter(j=>['proposal','negotiation','contract'].includes(j.status)).length}</strong></div><div><TicketCheck/><span>Shows confirmados</span><strong>{jobs.filter(j=>j.status==='confirmed').length}</strong></div><div><CalendarDays/><span>Próximos eventos</span><strong>{jobs.filter(j=>j.event_date).length}</strong></div></section>
  <section id="eventos" className="contractorPanel"><div className="contractorPanelHead"><div><span className="contractorEyebrow">MEUS EVENTOS</span><h2>Shows e negociações</h2></div></div>{jobs.length?<div className="contractorJobs">{jobs.map(j=><article key={j.id} className="contractorJob"><div className="contractorJobTop"><span className={`jobStatus ${j.status}`}>{statusLabel[j.status]||j.status}</span><strong>{j.event_date?new Date(`${j.event_date}T12:00:00`).toLocaleDateString('pt-BR'):'Data a definir'}</strong></div><h3>{j.title}</h3><p><MapPin size={15}/>{[j.venue,j.city,j.state].filter(Boolean).join(' • ')||'Local a definir'}</p>{j.proposal_value&&<div className="jobValue"><small>Proposta</small><strong>{Number(j.proposal_value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div>}<div className="jobFiles">{j.proposal_url&&<a href={j.proposal_url} target="_blank" rel="noreferrer"><FileText size={15}/>Proposta</a>}{j.contract_url&&<a href={j.contract_url} target="_blank" rel="noreferrer"><FileText size={15}/>Contrato</a>}{j.rider_url&&<a href={j.rider_url} target="_blank" rel="noreferrer"><FileText size={15}/>Rider</a>}</div></article>)}</div>:<div className="contractorEmpty">Nenhum evento vinculado ao seu acesso ainda.</div>}</section>
  <section id="dados" className="contractorPanel"><span className="contractorEyebrow">CADASTRO</span><h2>Meus dados</h2><div className="contractorFormGrid"><Field label="Nome" value={profile?.name} onChange={v=>setProfile(p=>({...p,name:v}))}/><Field label="Empresa / produtor" value={profile?.company} onChange={v=>setProfile(p=>({...p,company:v}))}/><Field label="CPF / CNPJ" value={profile?.document} onChange={v=>setProfile(p=>({...p,document:v}))}/><Field label="Telefone" value={profile?.phone} onChange={v=>setProfile(p=>({...p,phone:v}))}/><Field label="Cidade" value={profile?.city} onChange={v=>setProfile(p=>({...p,city:v}))}/><Field label="UF" value={profile?.state} onChange={v=>setProfile(p=>({...p,state:v}))}/></div><button className="contractorPrimary inline" onClick={saveProfile}><Save size={16}/>Salvar dados</button></section>
  </main></div>;
}
