import React from 'react';
import { ArrowLeft, BriefcaseBusiness, CalendarDays, FileText, Plus, Save, Trash2 } from 'lucide-react';
import { getAdminSession } from './contentStore';
import { createJobAdmin, deleteJobAdmin, fetchContractorsAdmin, fetchJobsAdmin, updateJobAdmin } from './contractorAdminStore';

const statuses=['lead','proposal','negotiation','contract','confirmed','completed','cancelled'];
const statusLabel={lead:'Consulta',proposal:'Proposta',negotiation:'Negociação',contract:'Contrato',confirmed:'Confirmado',completed:'Realizado',cancelled:'Cancelado'};
function Field({label,value,onChange,type='text'}){return <label className="adminField"><span>{label}</span><input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,children}){return <label className="adminField"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)}>{children}</select></label>}

export default function ContractorsAdmin(){
 const[contractors,setContractors]=React.useState([]),[jobs,setJobs]=React.useState([]),[loading,setLoading]=React.useState(true),[error,setError]=React.useState(''),[notice,setNotice]=React.useState('');
 const session=getAdminSession();
 const load=async()=>{setLoading(true);setError('');try{const[c,j]=await Promise.all([fetchContractorsAdmin(),fetchJobsAdmin()]);setContractors(c);setJobs(j)}catch(e){setError(e.message||'Falha ao carregar.')}finally{setLoading(false)}};
 React.useEffect(()=>{if(!session){window.location.href='/admin';return;}load()},[]);
 const add=async contractor=>{try{await createJobAdmin({contractor_id:contractor.user_id,title:'Show Lucas Venutto',city:contractor.city||'',state:contractor.state||'',status:'lead'});await load();setNotice('Evento criado.')}catch(e){setError(e.message)}};
 const patch=(id,key,value)=>setJobs(v=>v.map(j=>j.id===id?{...j,[key]:value}:j));
 const save=async job=>{try{const{contractor_id,...data}=job;await updateJobAdmin(job.id,data);setNotice('Evento atualizado.');setTimeout(()=>setNotice(''),2200)}catch(e){setError(e.message)}};
 const remove=async id=>{try{await deleteJobAdmin(id);setJobs(v=>v.filter(j=>j.id!==id))}catch(e){setError(e.message)}};
 return <div className="adminShell"><aside className="adminSidebar"><div><strong>Lucas Venutto</strong><small>Contratantes</small></div><a href="/admin"><ArrowLeft size={17}/>Voltar ao CMS</a><a href="/contratante" target="_blank" rel="noreferrer"><BriefcaseBusiness size={17}/>Ver portal</a></aside><main className="adminMain"><header className="adminTop"><div><span className="adminEyebrow">COMERCIAL</span><h1>Contratantes</h1></div></header>{error&&<div className="adminNotice error">{error}</div>}{notice&&<div className="adminNotice">{notice}</div>}{loading?<div className="adminPanel">Carregando...</div>:<>
 <section className="adminPanel"><h2>Cadastros</h2><div className="contractorAdminGrid">{contractors.length?contractors.map(c=><article className="contractorAdminCard" key={c.user_id}><div><strong>{c.name||c.company||c.email}</strong><span>{c.company}</span><small>{c.email} • {c.phone}</small><small>{[c.city,c.state].filter(Boolean).join(' / ')}</small></div><button className="smallPrimary" onClick={()=>add(c)}><Plus size={15}/>Novo evento</button></article>):<p className="adminHelp">Nenhum contratante cadastrado ainda.</p>}</div></section>
 <section className="adminPanel"><h2>Eventos e negociações</h2>{jobs.length?jobs.map(j=><div className="adminItem" key={j.id}><div className="adminGrid"><Select label="Contratante" value={j.contractor_id} onChange={v=>patch(j.id,'contractor_id',v)}>{contractors.map(c=><option key={c.user_id} value={c.user_id}>{c.name||c.company||c.email}</option>)}</Select><Select label="Status" value={j.status} onChange={v=>patch(j.id,'status',v)}>{statuses.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</Select><Field label="Evento" value={j.title} onChange={v=>patch(j.id,'title',v)}/><Field label="Data" type="date" value={j.event_date} onChange={v=>patch(j.id,'event_date',v)}/><Field label="Hora" type="time" value={j.event_time} onChange={v=>patch(j.id,'event_time',v)}/><Field label="Cidade" value={j.city} onChange={v=>patch(j.id,'city',v)}/><Field label="UF" value={j.state} onChange={v=>patch(j.id,'state',v)}/><Field label="Local" value={j.venue} onChange={v=>patch(j.id,'venue',v)}/><Field label="Endereço" value={j.address} onChange={v=>patch(j.id,'address',v)}/><Field label="Público" type="number" value={j.audience} onChange={v=>patch(j.id,'audience',v)}/><Field label="Valor proposta" type="number" value={j.proposal_value} onChange={v=>patch(j.id,'proposal_value',v)}/><Field label="Sinal" type="number" value={j.signal_value} onChange={v=>patch(j.id,'signal_value',v)}/><Field label="Link proposta" value={j.proposal_url} onChange={v=>patch(j.id,'proposal_url',v)}/><Field label="Link contrato" value={j.contract_url} onChange={v=>patch(j.id,'contract_url',v)}/><Field label="Link rider" value={j.rider_url} onChange={v=>patch(j.id,'rider_url',v)}/><Field label="Link nota/fatura" value={j.invoice_url} onChange={v=>patch(j.id,'invoice_url',v)}/></div><div className="adminItemActions"><button className="smallPrimary" onClick={()=>save(j)}><Save size={15}/>Salvar</button><button className="danger" onClick={()=>remove(j.id)}><Trash2 size={15}/>Excluir</button></div></div>):<p className="adminHelp">Nenhum evento criado.</p>}</section>
 </>}</main></div>;
}
