import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { Music2, CalendarDays, CalendarPlus, MapPin, ArrowUpRight, Menu, X, Play, Pause, Mail, MessageCircle, Home, Video, Ticket, Instagram } from 'lucide-react';
import heroPhoto from './_DSC3661.jpg';
import storyPhoto from './_DSC4037 (1).jpg';
import featuredVideo from './WhatsApp Video 2026-09-01 at 12.24.27.mp4';
import artistLogo from './LOGO LUCAS VENUTTO (1).png';
import headerLogo from './logo lucas venutto.png';
import Admin from './Admin';
import { loadContent, subscribeContent } from './contentStore';
import './styles.css';

const monthNames=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];
const fade={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.55}};
function mapUrl(show){const target=show.address&&show.address!=='Endereço a confirmar'?`${show.venue}, ${show.address}, ${show.city}, ${show.state}`:`${show.city}, ${show.state}`;return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(target)}`;}
function calendarUrl(show){if(!show.date)return '#';const d=show.date.replaceAll('-','');const start=(show.time||'21:00').replace(':','')+'00';const endH=String((Number((show.time||'21:00').slice(0,2))+2)%24).padStart(2,'0');const end=endH+(show.time||'21:00').slice(3,5)+'00';const title=`Lucas Venutto - ${show.city}/${show.state}`;const loc=show.address?`${show.venue} - ${show.address} - ${show.city}/${show.state}`:`${show.city}/${show.state}`;return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${d}T${start}/${d}T${end}&location=${encodeURIComponent(loc)}`;}
function dateParts(date){if(!date)return {day:'--',month:'---'};const d=new Date(`${date}T12:00:00`);return {day:String(d.getDate()).padStart(2,'0'),month:monthNames[d.getMonth()]};}

function App(){
  const[content,setContent]=React.useState(loadContent());const[open,setOpen]=React.useState(false);const[playing,setPlaying]=React.useState(false);const[spotifyReady,setSpotifyReady]=React.useState(false);const controllerRef=React.useRef(null);
  const headerLogoSrc=content.media?.headerLogoUrl||headerLogo;const heroLogoSrc=content.media?.heroLogoUrl||artistLogo;const heroPhotoSrc=content.media?.heroImageUrl||heroPhoto;const storyPhotoSrc=content.media?.storyImageUrl||storyPhoto;const featuredVideoSrc=content.media?.featuredVideoUrl||featuredVideo;
  React.useEffect(()=>subscribeContent(setContent),[]);
  React.useEffect(()=>{let cancelled=false;const init=(api)=>{if(cancelled||controllerRef.current)return;const el=document.getElementById('spotify-controller');if(!el)return;api.createController(el,{uri:content.music.spotifyArtistUri,width:'100%',height:80},c=>{controllerRef.current=c;setSpotifyReady(true);c.addListener('playback_update',e=>e?.data&&setPlaying(!e.data.isPaused));});};if(window.SpotifyIframeApi)init(window.SpotifyIframeApi);window.onSpotifyIframeApiReady=api=>{window.SpotifyIframeApi=api;init(api)};if(!document.querySelector('script[data-spotify-iframe-api]')){const s=document.createElement('script');s.src='https://open.spotify.com/embed/iframe-api/v1';s.async=true;s.dataset.spotifyIframeApi='1';document.body.appendChild(s)}return()=>{cancelled=true}},[content.music.spotifyArtistUri]);
  const toggle=()=>{const c=controllerRef.current;if(!c)return;playing?c.pause():c.play()};
  const wa=`https://wa.me/${content.booking.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de informações para contratação do show de Lucas Venutto.\n\nCidade:\nData:\nEvento:\nPúblico estimado:')}`;
  const nav=[['musica','Música'],['agenda','Agenda'],['videos','Vídeos'],['sobre','Sobre'],['imprensa','Imprensa']];
  return <div className="siteV2"><header className="topbarV2"><a href="#inicio" className="brandLink"><img src={headerLogoSrc} alt={content.brand.artist}/></a><nav>{nav.map(([id,l])=><a key={id} href={`#${id}`}>{l}</a>)}<a className="bookBtn" href={wa} target="_blank" rel="noreferrer">Contrate</a></nav><button className="mobileMenuBtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{open&&<div className="mobileMenu">{nav.map(([id,l])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{l}</a>)}<a href={wa} target="_blank" rel="noreferrer">Contrate</a></div>}</header><main>
  <section id="inicio" className="heroV2"><div className="heroBg" style={{backgroundImage:`url(${heroPhotoSrc})`}}/><div className="heroShade"/><motion.div className="heroCopy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span className="eyebrow">{content.hero.eyebrow}</span><img src={heroLogoSrc} className="heroLogo" alt={content.brand.artist}/><h1>{content.hero.title}</h1><p>{content.hero.subtitle}</p><div className="heroActions"><button className="primaryCta" onClick={toggle} disabled={!spotifyReady}>{playing?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{playing?'Pausar':content.hero.primaryLabel}</button><a className="secondaryCta" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={17}/>{content.hero.secondaryLabel}</a></div></motion.div><div className="heroReleaseTag">2026 • NOVA FASE</div></section>
  <section className="tickerV2"><button onClick={toggle} disabled={!spotifyReady} className="tickerControl">{playing?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}<span>{playing?'TOCANDO':'OUVIR'}</span></button><div id="spotify-controller" className="spotifyController"/><div className="tickerMarquee"><div><strong>{content.ticker.title}</strong><span>•</span><em>{content.ticker.lyric}</em><span>•</span><strong>{content.ticker.title}</strong><span>•</span><em>{content.ticker.lyric}</em></div></div></section>
  <section id="musica" className="sectionV2 musicSection"><div className="sectionHead"><span className="eyebrow">DISCOGRAFIA</span><h2>{content.music.title}</h2><p>{content.music.intro}</p></div><div className="musicLayout"><motion.div className="spotifyBig" {...fade}><iframe title="Lucas Venutto no Spotify" src={content.music.spotifyEmbedUrl} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/></motion.div><motion.div className="releaseSide" {...fade}><div className="releaseFeatured"><span>ÚLTIMO LANÇAMENTO</span><h3>{content.hero.title}</h3><p>Single • 2026</p><button onClick={toggle}><Play size={15} fill="currentColor"/>Ouvir agora</button></div><div className="releaseFilters"><button className="active">Todos</button><button>Singles</button><button>EPs</button><button>Álbuns</button></div><div className="releaseList">{content.music.releases.map(r=><a key={r.id} href={r.spotifyUrl||content.music.spotifyArtistUrl} target="_blank" rel="noreferrer" className="releaseRow"><div className="releaseCover">{r.coverUrl?<img src={r.coverUrl} alt=""/>:<Music2/>}</div><div><strong>{r.title}</strong><span>{r.type} • {r.year}</span></div><ArrowUpRight size={16}/></a>)}</div><div className="platformLinks"><a href={content.music.spotifyArtistUrl} target="_blank" rel="noreferrer">Spotify</a><a href={content.social.apple} target="_blank" rel="noreferrer">Apple Music</a><a href={content.social.youtube} target="_blank" rel="noreferrer">YouTube</a><a href={content.social.amazon} target="_blank" rel="noreferrer">Amazon</a></div></motion.div></div></section>
  <section id="agenda" className="sectionV2 agendaV2"><div className="sectionHead inline"><div><span className="eyebrow">NA ESTRADA</span><h2>Agenda</h2></div><p>Próximas apresentações</p></div><div className="showCards">{content.shows.length?content.shows.map((s,i)=>{const d=dateParts(s.date);return <motion.article className="showCard" key={s.id} {...fade} transition={{duration:.45,delay:i*.05}}><div className="dateBlock"><strong>{d.day}</strong><span>{d.month}</span></div><div className="showMain"><h3>{s.city} <small>/ {s.state}</small></h3><strong className="venue">{s.private?'Evento privado':s.venue}</strong>{!s.private&&<a href={mapUrl(s)} target="_blank" rel="noreferrer" className="mapLink"><MapPin size={14}/>{s.address==='Endereço a confirmar'?`Ver ${s.city} no mapa`:s.address}</a>}</div><div className="showBtns">{s.ticketUrl&&<a href={s.ticketUrl} target="_blank" rel="noreferrer"><Ticket size={15}/>Ingressos</a>}<a href={calendarUrl(s)} target="_blank" rel="noreferrer"><CalendarPlus size={15}/>Salvar</a></div></motion.article>}):<div className="emptyState">Novas datas em breve.</div>}</div></section>
  <section id="videos" className="sectionV2 videoSection"><div className="sectionHead"><span className="eyebrow">AO VIVO</span><h2>Vídeos</h2><p>Palco, bastidores e momentos da carreira.</p></div><div className="videoFeature"><video src={featuredVideoSrc} muted loop autoPlay playsInline/><div className="videoOverlay"><h3>Sinta o palco.<br/>Viva o momento.</h3><a href={content.social.youtube} target="_blank" rel="noreferrer"><Play fill="currentColor"/>Assistir no YouTube</a></div></div><div className="videoGrid">{content.videos.map(v=><a className="videoCard" key={v.id} href={v.youtubeUrl} target="_blank" rel="noreferrer"><div className="videoThumb" style={v.thumbnailUrl?{backgroundImage:`url(${v.thumbnailUrl})`}:{}}><Play fill="currentColor"/></div><strong>{v.title}</strong><span>Assistir vídeo</span></a>)}</div></section>
  <section id="sobre" className="sectionV2 aboutV2"><motion.div className="aboutCopy" {...fade}><span className="eyebrow">{content.about.kicker}</span><h2>{content.about.title}</h2><p>{content.about.text}</p><div className="aboutStats"><div><strong>2026</strong><span>Nova fase</span></div><div><strong>SP</strong><span>Brasil</span></div><div><strong>AO VIVO</strong><span>Verdade no palco</span></div></div></motion.div><motion.div className="aboutPhoto" {...fade} style={{backgroundImage:`url(${storyPhotoSrc})`}}/></section>
  <section id="imprensa" className="sectionV2 pressV2"><div className="sectionHead"><span className="eyebrow">IMPRENSA</span><h2>{content.press.title}</h2><p>{content.press.text}</p></div><div className="pressGrid"><a href={content.press.pressKitUrl} target="_blank" rel="noreferrer">Release <ArrowUpRight/></a><a href={content.press.pressKitUrl} target="_blank" rel="noreferrer">Fotos oficiais <ArrowUpRight/></a><a href={content.press.pressKitUrl} target="_blank" rel="noreferrer">Logos <ArrowUpRight/></a><a href={content.press.pressKitUrl} target="_blank" rel="noreferrer">Press kit PDF <ArrowUpRight/></a></div></section>
  <section className="bookingV2"><div><span className="eyebrow dark">SHOWS & EVENTOS</span><h2>{content.booking.title}</h2><p>{content.booking.subtitle}</p></div><div className="bookingActions"><a href={wa} target="_blank" rel="noreferrer"><MessageCircle/>Solicitar orçamento</a><a href={`mailto:${content.booking.email}`}><Mail/>E-mail</a></div></section>
  <section className="fanClub"><div><span className="eyebrow">FIQUE PERTO</span><h2>Não perca os próximos lançamentos.</h2><p>Entre na lista VIP e receba novidades de músicas, agenda e bastidores.</p></div><a href={wa} target="_blank" rel="noreferrer">Entrar na lista VIP <ArrowUpRight/></a></section>
  </main><footer className="footerV2"><img src={headerLogoSrc} alt={content.brand.artist}/><div className="footerSocial"><a href={content.social.instagram}><Instagram/></a><a href={content.social.youtube}><Video/></a><a href={content.music.spotifyArtistUrl}><Music2/></a></div><span>© 2026 Lucas Venutto</span></footer>
  <nav className="mobileBottomNav"><a href="#inicio"><Home/><span>Início</span></a><a href="#musica"><Music2/><span>Música</span></a><a href="#agenda"><CalendarDays/><span>Agenda</span></a><a href="#videos"><Video/><span>Vídeos</span></a><a href={wa} target="_blank" rel="noreferrer"><MessageCircle/><span>Contrate</span></a></nav>
  <div className={`stickyPlayer ${playing?'isPlaying':''}`}><button onClick={toggle}>{playing?<Pause/>:<Play fill="currentColor"/>}</button><div><strong>{content.hero.title}</strong><span>Lucas Venutto • Spotify</span></div><div className="playerPulse"/></div></div>;
}
const isAdmin=window.location.pathname.replace(/\/+$/,'')==='/admin';
createRoot(document.getElementById('root')).render(isAdmin?<Admin/>:<App/>);
